#!/bin/env ruby
# encoding: utf-8
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'TestProject' do
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'DatePickerDialog'
pod 'CVCalendar', '~> 1.5.0'

end
